# Generated by Django 4.2.1 on 2023-08-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0012_gene_stable_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellmarker",
            name="species",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cell_markers",
                to="lnschema_bionty.species",
            ),
        ),
        migrations.AlterField(
            model_name="gene",
            name="species",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="genes",
                to="lnschema_bionty.species",
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="species",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proteins",
                to="lnschema_bionty.species",
            ),
        ),
    ]
