# Generated by Django 4.2.5 on 2023-12-09 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0020_alter_organism_bionty_source"),
        ("lnschema_core", "0031_rename_file_to_artifact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cellline",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="cellmarker",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="celltype",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="developmentalstage",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="disease",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="ethnicity",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="experimentalfactor",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="gene",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="organism",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="pathway",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="phenotype",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="protein",
            old_name="files",
            new_name="artifacts",
        ),
        migrations.RenameField(
            model_name="tissue",
            old_name="files",
            new_name="artifacts",
        ),
    ]
