# Generated by Django 4.2.5 on 2023-10-12 09:03

import django.db.models.deletion
import lnschema_core.users
from django.db import migrations, models

import lnschema_bionty.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lnschema_core", "0001_initial_squashed_0023"),
    ]

    operations = []  # type: ignore
