# Generated by Django 4.2.1 on 2023-06-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gene",
            old_name="gene_type",
            new_name="biotype",
        ),
        migrations.RemoveField(
            model_name="cellmarker",
            name="gene_name",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="omim_id",
        ),
        migrations.RemoveField(
            model_name="protein",
            name="ensembl_transcript_ids",
        ),
        migrations.RemoveField(
            model_name="protein",
            name="gene_symbols",
        ),
        migrations.RemoveField(
            model_name="protein",
            name="gene_synonyms",
        ),
        migrations.RemoveField(
            model_name="protein",
            name="uniprotkb_name",
        ),
        migrations.AddField(
            model_name="protein",
            name="gene_symbol",
            field=models.CharField(db_index=True, default=None, max_length=64, null=True),
        ),
    ]
