# Generated by Django 4.2.1 on 2023-06-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0002_rename_gene_type_gene_biotype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biontysource",
            name="entity",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="biontysource",
            name="source",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="biontysource",
            name="species",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="biontysource",
            name="version",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="cellline",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cellmarker",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="celltype",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pathway",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="readout",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="tissue",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=256),
            preserve_default=False,
        ),
    ]
