# Generated by Django 4.2.1 on 2023-07-17 14:22

from django.db import migrations


def rename_in_bionty_source():
    """Rename Readout entity in BiontySource table."""
    from lnschema_bionty import BiontySource

    BiontySource.objects.filter(entity="Readout").update(entity="ExperimentalFactor")


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0008_file_hash_type_transform_parents"),
        (
            "lnschema_bionty",
            "0006_alter_biontysource_options_alter_cellline_options_and_more",
        ),
    ]

    operations = [migrations.RenameModel(old_name="Readout", new_name="ExperimentalFactor")]
