# Generated by Django 4.2.1 on 2023-07-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0007_rename_readout_experimental_factor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gene",
            name="hgnc_id",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="mgi_id",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="ncbi_gene_id",
        ),
        migrations.RemoveField(
            model_name="protein",
            name="ncbi_gene_ids",
        ),
        migrations.AddField(
            model_name="gene",
            name="ncbi_gene_ids",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="protein",
            name="ensembl_gene_ids",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="cellmarker",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="gene",
            name="ensembl_gene_id",
            field=models.CharField(db_index=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="protein",
            name="uniprotkb_id",
            field=models.CharField(db_index=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=64),
        ),
    ]
