# Generated by Django 4.2.5 on 2023-10-11 13:34

from pathlib import Path

import lamindb_setup as ln_setup
from django.db import migrations

import lnschema_bionty.models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0001_initial_squashed_0016"),
    ]

    operations = []  # type: ignore
