# Generated by Django 4.2.1 on 2023-10-23 14:26

from django.db import IntegrityError, migrations, models, transaction

import lnschema_bionty.ids


class Migration(migrations.Migration):
    dependencies = [
        (
            "lnschema_bionty",
            "0018_organism_rename_species_biontysource_organism_and_more",
        ),
    ]

    operations = []  # type: ignore
