# Generated by Django 4.2.5 on 2023-12-09 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0020_alter_organism_bionty_source"),
    ]

    operations = []  # type: ignore
