# Generated by Django 4.2.9 on 2024-01-09 07:41

import django.db.models.deletion
import lnschema_core.users
from django.db import IntegrityError, migrations, models, transaction


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0022_rename_datasets_cellline_collections_and_more"),
    ]

    operations = []  # type: ignore
