# Generated by Django 5.1 on 2024-07-09 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_bionty", "0029_alter_cellline_previous_runs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifactcellline",
            old_name="cell_line_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactcellmarker",
            old_name="cell_marker_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactcelltype",
            old_name="cell_type_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactdevelopmentalstage",
            old_name="developmental_stage_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactdisease",
            old_name="disease_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactethnicity",
            old_name="ethnicity_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactexperimentalfactor",
            old_name="experimental_factor",
            new_name="experimentalfactor",
        ),
        migrations.RenameField(
            model_name="artifactexperimentalfactor",
            old_name="experimental_factor_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactgene",
            old_name="gene_ref_is_symbol",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactorganism",
            old_name="organism_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactpathway",
            old_name="pathway_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactphenotype",
            old_name="phenotype_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifactprotein",
            old_name="protein_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="artifacttissue",
            old_name="tissue_ref_is_name",
            new_name="label_ref_is_name",
        ),
    ]
